package org.ice.module;

import org.ice.Config;

public class ErrorHandler extends HttpModule implements IErrorHandler {
	
	private Exception exception;
	
	public Exception getException() {
		return exception;
	}

	public void setException(Exception ex) {
		this.exception = ex;
	}
	
	public void errorTask()	{
		setContentType("text/html");
		echo("<h2>Error occurred</h2>");
		echo("<b>Detail:</b> "+exception.toString());
		StackTraceElement[] stacks = exception.getStackTrace();
		echo("<br /><h4>Stack Trace:</h4>");
		echo("<div style='margin: -10px 0 0 50px'>");
		for(StackTraceElement element: stacks)	{
			echo(element.toString()+"<br />");
		}
		echo("</div>");
		echo("<hr /><i>This report is automatically generated by Ice Framework "+Config.version+"</i>");
	}
}
