package org.ice.module;

import org.ice.exception.IceException;
import org.ice.http.HttpRequest;
import org.ice.http.HttpResponse;

public interface IModule {
	
	public void setRequest(HttpRequest request);
	
	public HttpRequest getRequest();
	
	/**
	 * Lifecycle callback method
	 * Called just after the controller has been initialized
	 * You should do some variables initialization only
	 */
	public void init();
	
	/**
	 * Lifecycle callback method
	 * Called before the request is dispatched
	 * You should do some filterings/validations only
	 */
	public void preDispatch() throws Exception;
	
	/**
	 * Lifecycle callback method
	 * Dispatch the request
	 * @throws IceException 
	 */
	public void dispatch(String task) throws Exception;
	
	/**
	 * Lifecycle callback method
	 * Called after the request is dispatched
	 * You should do some stuffs which are common in all request
	 */
	public void postDispatch() throws Exception;
	
	/**
	 * Get the response generated by this module
	 * @return the response
	 */
	public String getStreamResponse();
	
	/**
	 * Lifecycle callback method
	 * Called just before the request finished
	 */
	public void destroy();

	public HttpResponse getResponse();
	
	public void setResponse(HttpResponse response);
	
	public void setHeader(String headerName, String value);
	
	public String getHeader(String headerName);
	
}
